LANGUAGES = {
    "en": {
        "language_name": "English",
        "start": "Welcome to Jambo! Please choose your role:",
        "choose_language": "Please select your language:",
        "role_driver": "Driver",
        "role_passenger": "Passenger",
        "role_taxi": "Taxi",
        "search_trip": "Search for a trip",
        "create_trip": "Create a trip",
        "book_trip": "Book a trip",
        "back": "Back",
    },
    "ru": {
        "language_name": "Русский",
        "start": "Добро пожаловать в Jambo! Пожалуйста, выберите свою роль:",
        "choose_language": "Пожалуйста, выберите язык:",
        "role_driver": "Водитель",
        "role_passenger": "Пассажир",
        "role_taxi": "Такси",
        "search_trip": "Найти поездку",
        "create_trip": "Создать поездку",
        "book_trip": "Забронировать поездку",
        "back": "Назад",
    },
    "uk": {
        "language_name": "Українська",
        "start": "Ласкаво просимо до Jambo! Оберіть вашу роль:",
        "choose_language": "Будь ласка, виберіть мову:",
        "role_driver": "Водій",
        "role_passenger": "Пасажир",
        "role_taxi": "Таксі",
        "search_trip": "Пошук поїздки",
        "create_trip": "Створити поїздку",
        "book_trip": "Забронювати поїздку",
        "back": "Назад",
    },
    "kk": {
        "language_name": "Қазақ тілі",
        "start": "Jambo-ға қош келдіңіз! Өзіңіздің рөліңізді таңдаңыз:",
        "choose_language": "Тілді таңдаңыз:",
        "role_driver": "Жүргізуші",
        "role_passenger": "Жолаушы",
        "role_taxi": "Такси",
        "search_trip": "Сапарды іздеу",
        "create_trip": "Сапар құру",
        "book_trip": "Сапарды брондау",
        "back": "Артқа",
    },
    "uz": {
        "language_name": "O'zbekcha",
        "start": "Jambo-ga xush kelibsiz! Iltimos, rolingizni tanlang:",
        "choose_language": "Iltimos, tilni tanlang:",
        "role_driver": "Haydovchi",
        "role_passenger": "Yo‘lovchi",
        "role_taxi": "Taksi",
        "search_trip": "Safarni qidiring",
        "create_trip": "Safarni yarating",
        "book_trip": "Safarni bron qiling",
        "back": "Orqaga",
    },
    "az": {
        "language_name": "Azərbaycan dili",
        "start": "Jambo-ya xoş gəlmisiniz! Zəhmət olmasa rolunuzu seçin:",
        "choose_language": "Zəhmət olmasa dil seçin:",
        "role_driver": "Sürücü",
        "role_passenger": "Sərnişin",
        "role_taxi": "Taksi",
        "search_trip": "Səyahəti axtarın",
        "create_trip": "Səyahət yarat",
        "book_trip": "Səyahəti bron et",
        "back": "Geri",
    },
    "hy": {
        "language_name": "Հայերեն",
        "start": "Բարի գալուստ Jambo! Խնդրում ենք ընտրել ձեր դերը:",
        "choose_language": "Խնդրում ենք ընտրել լեզուն:",
        "role_driver": "Վարորդ",
        "role_passenger": "Ուղևոր",
        "role_taxi": "Տաքսի",
        "search_trip": "Որոնել ուղևորություն",
        "create_trip": "Ստեղծել ուղևորություն",
        "book_trip": "Ամրագրել ուղևորություն",
        "back": "Հետ",
    },
    "ka": {
        "language_name": "ქართული",
        "start": "კეთილი იყოს თქვენი მობრძანება Jambo-ში! გთხოვთ, აირჩიოთ თქვენი როლი:",
        "choose_language": "გთხოვთ, აირჩიოთ ენა:",
        "role_driver": "მძღოლი",
        "role_passenger": "მგზავრი",
        "role_taxi": "ტაქსი",
        "search_trip": "მოგზაურობის ძებნა",
        "create_trip": "მოგზაურობის შექმნა",
        "book_trip": "დაჯავშნა",
        "back": "უკან",
    },
    "ro": {
        "language_name": "Română",
        "start": "Bine ați venit la Jambo! Vă rugăm să alegeți rolul:",
        "choose_language": "Vă rugăm să selectați limba:",
        "role_driver": "Șofer",
        "role_passenger": "Pasager",
        "role_taxi": "Taxi",
        "search_trip": "Caută o călătorie",
        "create_trip": "Creează o călătorie",
        "book_trip": "Rezervă o călătorie",
        "back": "Înapoi",
    },
    "tr": {
        "language_name": "Türkçe",
        "start": "Jambo'ya hoş geldiniz! Lütfen rolünüzü seçin:",
        "choose_language": "Lütfen dili seçin:",
        "role_driver": "Sürücü",
        "role_passenger": "Yolcu",
        "role_taxi": "Taksi",
        "search_trip": "Seyahat ara",
        "create_trip": "Seyahat oluştur",
        "book_trip": "Seyahati ayırt",
        "back": "Geri",
    },

    # Остальные языки мира:
    "es": {"language_name": "Español", "start": "...", "choose_language": "...", "role_driver": "...", "role_passenger": "...", "role_taxi": "...", "search_trip": "...", "create_trip": "...", "book_trip": "...", "back": "..."},
    "fr": {"language_name": "Français", ...},
    "de": {"language_name": "Deutsch", ...},
    "pl": {"language_name": "Polski", ...},
    "it": {"language_name": "Italiano", ...},
    "pt": {"language_name": "Português", ...},
    "fa": {"language_name": "فارسی", ...},
    "zh": {"language_name": "中文", ...},
    "ja": {"language_name": "日本語", ...},
    "hi": {"language_name": "हिन्दी", ...}
}
